### ISSUE TITLE
Safari scrolling doesn't work

### ISSUE THREAD

**Issue by cabal-daniel** [react-pdf-viewer/react-pdf-viewer#474]
This is how I'm deploying the code

```
import React, { useState } from 'react';
import { Worker, Viewer } from '@react-pdf-viewer/core';
import { defaultLayoutPlugin } from '@react-pdf-viewer/default-layout';

import '@react-pdf-viewer/default-layout/lib/styles/index.css';
import 'react-pdf/dist/esm/Page/AnnotationLayer.css';

const documentURL = "..."

function App() {
    
    const defaultLayoutPluginInstance = defaultLayoutPlugin();
    
    return (
        <div style={{
            height: 2000,
            width: 1000,
            overflowY: 'scroll'
          }}>
          <Worker workerUrl={`https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.min.js`}>
              <Viewer 
                fileUrl={documentURL}
                plugins={[
                    // Register plugins
                    defaultLayoutPluginInstance,
                ]}
              />
          </Worker>
        </div>
    );
}

export default App;
```

Works fine on Chrome, but the page changing widget and scrolling doesn't work

**Comment by phuoc-ng** [comment]
@cabal-daniel Please specify the unit of size

```js
<div style={{
            height: '2000px',
            width: '1000px',
}}>
```

**Comment by cabal-daniel** [comment]
It still doesn't seem to work

```
return (
        <div style={{
            height: '2000px',
            width: '1000px',
          }}>
          <Worker workerUrl={`https://unpkg.com/pdfjs-dist@2.6.347/build/pdf.worker.min.js`}>
              <Viewer 
                fileUrl={documentURL}
                plugins={[
                    // Register plugins
                    defaultLayoutPluginInstance,
                ]}
              />
          </Worker>
        </div>
    );
```

**Comment by cabal-daniel** [comment]
Looks like it's caused by some weird Safari CSS behaviours. The height 100% CSS for `rpv-default-layout-body` class should be converted to 1995px, which is the height of its container but it's the sum of the height of every single child element.

![Screen Shot 2021-02-27 at 2 09 07 PM](https://user-images.githubusercontent.com/65152299/109401782-80f0e380-7905-11eb-8f83-e4d0ab599f76.png)

**Comment by cabal-daniel** [comment]
Ok found a fix, you have to set `height: 100%` to `rpv-default-layout-main`. Apparently this is some weird behaviour using flex in Safari: https://stackoverflow.com/a/43421645/1712607

**Comment by phuoc-ng** [comment]
@cabal-daniel 
You're right. Thanks for reporting the issue.
I fixed it in the latest code, and the fix will be included in v2.4.1

**Comment by phuoc-ng** [comment]
@cabal-daniel 
v2.4.1 was [released](https://react-pdf-viewer.dev/updates). Please update.

**Comment by handofthecode** [comment]
I'm testing safari as well and I've got the latest version 2.4.1. The pdf will not change pages or scroll if the parent width/height dimensions are set using percentages.

**Comment by niels-bosman** [comment]
@phuocng This issue persist when not using the `defaultLayoutPlugin`. Can we re-open this?

**Comment by kgoedecke** [comment]
@phuocng ping about the re-open of the issue.

**Comment by kgoedecke** [comment]
@phuocng please re-open this.

**Comment by phuocng** [comment]
I'll revisit this issue.

**Comment by niels-bosman** [comment]
@phuocng Happening to me for Safari 17.2.1 with "@react-pdf-viewer/core" 3.12.0 and "pdfjs-dist" 3.11.174.

**Comment by niels-bosman** [comment]
@phuocng Is there any update on this?

**Comment by phuocng** [comment]
@niels-bosman I couldn't reproduce the issue with Safari 17.2.1. Here is my Safari version:

<img width="396" alt="Screenshot 2024-02-07 at 15 48 07" src="https://github.com/react-pdf-viewer/react-pdf-viewer/assets/57786711/cfcf6a37-0647-4760-b372-bfadb83c393a">

Can you let me know the sample code that I can see this issue?
