### ISSUE TITLE
Thumbnail image not rendering when switching PDFs and using custom renderThumbnailItem

### ISSUE THREAD

**Issue by LucasBer** [react-pdf-viewer/react-pdf-viewer#961]
Hi,

I was am using an application where you can switch between different PDF files. I noticed however that when I switch between PDFs that the thumbnail images are stuck on a loading spinner (or don't change if no spinner is implemented). 

I discovered that the custom `renderThumbnailItem` property on the `<Thumbnails/>` was causing this, and that when removing the property it works (= using default thumbnail item rendering) 

I have made a minimalistic sandbox to illustrate my issue: 

https://codesandbox.io/s/holy-dew-10594

Clicking on the button to switch between PDFs updates the `<Thumbnails/>` using the default thumbnail item rendering, but not the one using a custom `renderThumbnailItem `

Do I need to somehow adjust my renderThumbnailItem so that it can handle switching between PDFs? 

Thanks in advance!

**Comment by phuoc-ng** [comment]
@LucasBer Thanks for reporting the issue.
It was fixed in the latest code, and will be included in the next version.

Here is how this [example](https://github.com/react-pdf-viewer/react-pdf-viewer/blob/master/demo/nextjs/pages/thumbnail-render-thumbnail-item-dynamic-document/index.tsx) works

https://user-images.githubusercontent.com/57786711/149605043-64e26ae2-9cfd-46ae-b6c7-76ba384f628b.mp4

**Comment by LucasBer** [comment]
Thank you, looks great!

Do you have an estimation as to when the next update will release? 

Thanks in advance!

**Comment by phuoc-ng** [comment]
@LucasBer [v3.1.0](https://react-pdf-viewer.dev/updates/) is released. Please upgrade!

**Comment by LucasBer** [comment]
Hi @phuoc-ng 

I've installed the latest version of 3.1.0 but unfortunately I'm still encountering some issues. 

I have once again created a minimalistic sandbox, mimicking the simple behavior of switching between PDFs:

https://codesandbox.io/s/busy-wildflower-5czqc

Now switching between PDF's seems to not consistently load thumbnails for either <Thumbnails/> element, regardless whether or not you have a `renderThumbnailItem ` present.

Can you please check out the sandbox I've provided and notify me if there's anything I'm doing wrong? 

Thanks once again in advance!

**Comment by phuoc-ng** [comment]
@LucasBer It seems that it doesn't work when you use both `Thumbnails` instance such as

```js
<Thumbnails />
<Thumbnails renderThumbnailItem={customRender} />
```

Using one of them works properly. Does your use case want to have both of them at the same time?

**Comment by LucasBer** [comment]
> @LucasBer It seems that it doesn't work when you use both `Thumbnails` instance such as
> 
> ```js
> <Thumbnails />
> <Thumbnails renderThumbnailItem={customRender} />
> ```
> 
> Using one of them works properly. Does your use case want to have both of them at the same time?

@phuoc-ng  I am currently using an accordion from material UI to render the thumbnails. Only a single `<Thumbnails/>` is shown at a time because you can only have 1 open at a time (I have also tried giving the accordion the unmountOnExit property).

After switching a few times the Thumbnails start infinitely loading as previously described. I have updated my sandbox to illustrate my use-case.:

https://codesandbox.io/s/holy-dew-10594

Is this specific design something that's not supported then?

**Comment by phuoc-ng** [comment]
So that is a normal usage. I have tried to play with the sandbox by clicking the accordion a few times (with your codesandbox, and a version that uses the `renderThumbnailItem` as https://codesandbox.io/s/brave-sammet-fvx4i?file=/src/App.tsx). But I don't see any issues.

https://user-images.githubusercontent.com/57786711/151078732-41eb20bf-066f-4215-b57b-0dba53482e8b.mp4

Maybe I miss something there?

**Comment by LucasBer** [comment]
Using the sandbox you have linked I can replicate my issue quite easily, additionally an error gets thrown (but this is one of the first times I'm encountering this error)

https://user-images.githubusercontent.com/32563741/151173118-f7d4e6ef-139f-4ad1-afe5-871e208b14d6.mp4
